build image:
  stage: build
  image: docker:20
  services: [ docker:20-dind ]
  needs: []
  variables:
    IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
  script:
    - docker build -t ${IMAGE} .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push ${IMAGE}
